spring.application.name=exam
spring.datasource.url=jdbc:mysql://localhost:3306/ExamMCQS?createDatabaseIfNotExist=true&useUnicode=true
spring.datasource.username=root
spring.datasource.password=Dattu@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

 logging.level.org.springframework.web=DEBUG

 server.port=8082

spring.web.resources.static-locations=file:///C:/E-commerce/


# Set max file size and max request size (example: 10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

aws.access-key-id=AKIAZVMTUZENRBALOP4H
 	
aws.secret-access-key=8jRxEG/+flDOTZvDZ8WKpWucPwgQnaUwELMh3jZj

aws.region=ap-south-1
aws.s3.bucket-name=rjayb2b
aws.s3.endpoint-url=https://s3.ap-south-1.amazonaws.com
